////
Copyright (c)  2019  Janik Rabe

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the file 'COPYING.DOC'
////

oidentd_masq.conf(5)
====================
:doctype:      manpage
:man manual:   oidentd User Manual
:man source:   oidentd
:reproducible: yes
:revdate:      2021-08-16
:sysconfdir:   /etc


NAME
----

oidentd_masq.conf - oidentd NAT configuration file


DESCRIPTION
-----------

If NAT support is enabled with the *--masquerade* option, *oidentd* reads the
*{sysconfdir}/oidentd_masq.conf* file to determine Ident responses to queries
intended for other machines.  It is also possible to forward queries to Ident
servers on the hosts connecting through the machine *oidentd* runs on.  For more
information on forwarding, please see the *--forward* option in *oidentd*(8).

The NAT configuration file contains one rule per line.  Lines are read from top
to bottom, and only the first matching rule is used.  Lines starting with a
number sign ("#") are ignored.


RULE FORMAT
-----------

Rules must have the following form:

[subs="quotes"]
....
_host_[/_mask_] _response_ _system-type_
....

The _host_ field specifies the hostname or IP address of the host that owns the
connection for which an Ident query was received.  This host must be connecting
through the machine *oidentd* runs on.  The host may be specified as either an
IP address or a hostname.

If a network mask is specified using the _mask_ field, the rule applies to all
hosts in the given subnetwork.  Network masks may be specified in dot notation
(e.g., "255.255.192.0") or in CIDR notation (e.g., "18").

The _response_ field specifies the response to be sent when receiving a query
for the specified host or subnetwork.

The _system-type_ field specifies the operating system to send alongside the
Ident response.  See the *--other* option in *oidentd*(8) for more information.


EXAMPLES
--------

[subs="quotes"]
....
# host[/mask]           response  system-type
10.0.0.1                user1     UNIX
server.internal         user2     UNIX-BSD
10.0.0.0/24             user3     UNIX
10.0.0.0/255.255.0.0    user4     UNKNOWN
....

Note that the order of the rules is significant in this example.  Due to lines
being read from top to bottom, more specific rules must precede more general
ones.  For example, the rule for "10.0.0.1" would not match any connections if
it were preceded by the more general "10.0.0.0/24".


AUTHOR
------

mailto:info@janikrabe.com[Janik Rabe]::
  https://janikrabe.com/projects/oidentd/

Originally written by Ryan McCabe.


BUGS
----

Please report any bugs to mailto:info@janikrabe.com[Janik Rabe].


SEE ALSO
--------

*oidentd*(8)
*oidentd.conf*(5)
